export enum ReduxActionType {
  FETCHED_BIDS = 'FETCHED_BIDS',
  FETCHING_BIDS = 'FETCHING_BIDS',
  FETCH_BIDS = 'FETCH_BIDS',
  PLACE_BID = 'PLACE_BID',
  RETRACT_BID = 'RETRACT_BID',
  UPDATE_BID = 'UPDATE_BID',
}
